version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: nest-graphql-prisma-passport
    volumes:
      - db-data:/var/lib/postgresql/nest-graphql-prisma-passport/data
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
