version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: nest-graphql-prisma-passport
    volumes:
      - db-data:/var/lib/postgresql/nest-graphql-prisma-passport/data
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
    ports:
      - '16379:6379'
  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
